export default {
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 15,
  FONT_SIZE_LARGE: 20,
  PRIMARY_DARK_COLOR: '#22a6f1',
  SECONDARY_DARK_COLOR: '#a0dbfc',
  PRIMARY_ACCENT_COLOR: '#fce45e',
  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '600',
  FONT_WEIGHT_HEAVY: '900'
};